routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

Auth::routes(['verify' => true]);


Route::middleware('auth')->group(function () {
    Route::get('/', 'SiteController@home');
    Route::get('/elegir_sistema', 'SystemController@index')->name('system.select');
    Route::get('/dashboard/root', 'AdminController@root_dashboard')->name('root.dashboard');
});

Route::name('admin.')->middleware('auth')->group(function () {
    Route::resource('/sistemas', 'SystemController', ['names' => 'system']);
});

// TDS Routes
Route::post('/tds/activacion', 'TicketDistributionSystem\TicketDistributionSystemController@account_activation')->name('tds.account.activation');
Route::get('/tds/{id}/registro', 'TicketDistributionSystem\TicketDistributionSystemController@register')->name('tds.register');
Route::post('/tds/logout', 'TicketDistributionSystem\TicketDistributionSystemController@logout')->name('tds.logout');
Route::post('/tds/login', 'TicketDistributionSystem\TicketDistributionSystemController@login')->name('tds.login');
Route::get('/tds/login', 'TicketDistributionSystem\TicketDistributionSystemController@login_form')->name('tds.login.form');
Route::get('/tds', 'TicketDistributionSystem\TicketDistributionSystemController@index')->middleware('auth:client_users')->name('tds');
Route::get('/tds/{id}/asignar', 'TicketDistributionSystem\TicketDistributionSystemController@assign')->middleware('auth:client_users')->name('tds.assign');

// TDS password reset
Route::get('/tds/password/request', 'TicketDistributionSystem\TicketDistributionSystemController@password_request_form')->name('tds.password.request.form');
Route::get('/tds/{id}/password/reset', 'TicketDistributionSystem\TicketDistributionSystemController@password_reset_form')->name('tds.password.reset.form');
Route::post('/tds/email/reenviar', 'TicketDistributionSystem\TicketDistributionSystemController@resend_email')->middleware('auth:client_users')->name('tds.email.resend');
Route::post('/tds/password/request', 'TicketDistributionSystem\TicketDistributionSystemController@password_request')->name('tds.password.request');
Route::post('/tds/password/reset', 'TicketDistributionSystem\TicketDistributionSystemController@password_reset')->name('tds.password.reset');

// TDS Exports
Route::post('/tds/exportar', 'TicketDistributionSystem\TicketDistributionSystemController@export')->name('tds.export');


// Subdomain routes
Route::domain('{system}.' . env('APP_BASE_DOMAIN'))->name('system.')->middleware('auth')->group(function () {
    // Route::prefix('{pumastabasco}')->name('system.')->middleware('auth')->group(function () {
    Route::get('/', 'AdminController@dashboard_redirect');

    // System dashboard
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

    // Events
    Route::prefix('/eventos')->name('events.')->group(function () {
        // Event groups resource
        Route::resource('/grupos', 'EventGroupController', ['names' => 'groups']);
        Route::post('/grupos/{id}/upload_img', 'EventGroupController@upload_img')->name('groups.upload.imgs');
        Route::put('/grupos/{id}/update/ticket_types', 'EventGroupController@updateTicketTypes')->name('groups.update.ticket_types');
        Route::get('/grupos/{id}/general', 'EventGroupController@general')->name('groups.general');
        Route::get('/grupos/{id}/holding', 'EventGroupController@holding')->name('groups.holding');
        Route::get('/grupos/{id}/boletos', 'EventGroupController@orders')->name('groups.orders');
        Route::get('/grupos/{id}/zonas', 'EventGroupController@zones')->name('groups.zones');
        Route::get('/grupos/{id}/{order_id}/qrs', 'OrderController@qrs')->name('groups.order.qrs');
        Route::get('/grupos/{id}/boletos/generar', 'EventGroupController@ticket_qrs_single_page')->name('groups.season.tickets.generateQRs');

        // All, by venue or team
        Route::get('/todos', 'EventController@all')->name('all');
        Route::get('/sede/{venue}', 'EventController@byVenue')->name('byVenue');
        Route::get('/equipo/{team}', 'EventController@byTeam')->name('byTeam');

        // Edit
        Route::post('/{id}/upload_img', 'EventController@upload_img')->name('upload.imgs');
        Route::get('/{id}/change_status', 'EventController@change')->name('status');

        // Holding
        Route::get('/{id}/holding', 'EventController@holding')->name('tickets.holding');

        // Statistics | Readings | Tickets | Courtesy | Accreditations
        Route::get('/{id}/estadisticas', 'EventController@statistics')->name('statistics');
        Route::get('/{id}/estadisticas/generales', 'EventController@general_statistics')->name('general.statistics');
        Route::post('/{id}/estadisticas/pdf', 'EventController@stadistic_pdf')->name('statistics.pdf');
        Route::get('/{id}/estadisticas/procesar', 'EventController@processStatistics')->name('statistics.process');
        Route::get('/{id}/lecturas', 'EventController@ticket_readings')->name('tickets.readings');
        Route::get('/{id}/boletos', 'EventController@ticket_list')->name('tickets.list'); // Ticket
        Route::get('/{id}/boletos/generar', 'EventController@tickets_generate')->name('tickets.generate');

        Route::get('/{id}/boletos/generarQRs', 'EventController@ticket_qrs_single_page')->name('tickets.generateForEvent');
        Route::get('/{id}/boletos/reporte', 'EventController@order_report')->name('tickets.order_report');
        Route::post('/{id}/boletos/buscar', 'EventController@search')->name('tickets.search');
        Route::get('/{id}/cortesias', 'EventController@courtesy_list')->name('courtesy.list');
        Route::get('/{id}/cortesias/generar', 'EventController@courtesy_qrs_single_page')->name('courtesy.generateForEvent');
        Route::get('/{id}/acreditaciones', 'EventController@accreditations_list')->name('accreditations.list');
        Route::post('/{id}/distribucion', 'EventController@send_ticket_distribution')->name('tickets.distribution.send');
        Route::get('/{id}/distribucion/{ticket_group}/reenviar', 'EventController@resend_email')->name('tickets.distribution.resend');
        Route::get('/{id}/distribucion', 'EventController@ticket_distribution')->name('tickets.distribution');

        // Analysis
        Route::get('/{id}/analisis', 'EventController@analysis')->name('analysis');

        // Season tickets
        Route::get('/{id}/abonos', 'AccreditationController@seasonTickets')->name('season.tickets');
        Route::get('/{id}/abonos/generar', 'AccreditationController@generateSeasonTickets')->name('season.tickets.generate');
        Route::get('/{id}/abonos/{season_ticket}', 'AccreditationController@show')->name('season.tickets.show');

        // Order QRs
        Route::get('/{id}/{order_id}/qrs', 'OrderController@qrs')->name('order_qrs');

        // Cortesias group
        Route::prefix('/{id}/acreditaciones')->name('accreditations.')->group(function () {
            // Route::get('/seleccionar', 'EventController@accreditations')->name('selection'); // Vista usuario acreditaciones
            Route::get('/confirmar', 'AccreditationController@confirm_accreditations')->name('confirm');
            Route::get('/guardar', 'AccreditationController@store')->name('store');
            Route::get('/generar', 'EventController@generateAccreditations')->name('generateForEvent'); // Vista usuario acreditaciones

            Route::get('/{order}/detalle', 'OrderController@courtesy_detail')->name('courtesies.detail');

            Route::get('/{accreditation}', 'AccreditationController@show')->name('show');
            Route::put('/{accreditation}/update', 'AccreditationController@update')->name('update');
            // Route::get('/{accreditation}/show', 'AccreditationController@show')->name('show');
        });
    });

    // Resource
    Route::resource('/eventos', 'EventController', ['names' => 'events']);


    // Orders
    Route::resource('/ordenes', 'OrderController', ['names' => 'orders'])->except(['edit, update']);
    Route::post('/ordenes/{id}', 'OrderController@update')->name('orders.update');
    Route::get('/ordenes/{id}/pdf', 'OrderController@pdf')->name('courtesy.pdf');
    Route::get('/ordenes/{id}/email/resend', 'OrderController@resend_email')->name('orders.resend.email');
    // Route::get('/ordenes/{id}/qr', 'OrderController@Qrs');
    // Route::get('qrImage/{order_id}/{type}', 'SiteController@qrImage');
    // Route::resource('/temas', 'TopicController');
    // Route::get('/soporte', 'SupportController@index');
    // Route::get('/soporte/{id}/estado/{status}', 'SupportController@change_status');

    // Accreditations
    Route::prefix('/acreditaciones')->name('accreditations.')->group(function () {
        // Route::get('/', 'AccreditationController@index')->name('index');
        Route::get('/detalle/{id}', 'AccreditationController@accreditation_history')->name('details');
        Route::get('/qrs', 'AccreditationController@qr')->name('qr');
        Route::get('/qrs/{id}', 'AccreditationController@qr')->name('qrByTeam');
        Route::get('/importar', 'ImportController@index')->name('import');
        Route::post('/import', 'ImportController@import')->name('import.file');
        Route::post('/version/{acreditation}', 'AccreditationController@change_version')->name('version');
    });
    Route::resource('/acreditaciones', 'AccreditationController', ['names' => 'accreditations'])->except(['edit', 'destroy']);

    // Access
    Route::prefix('/accesos')->name('access.')->group(function () {
        Route::get('/reportes', 'Access\ReportController@reports')->name('reports');
        Route::get('/reportes/{id}', 'Access\ReportController@report')->name('report');
        Route::post('/importar', 'ImportController@import_access')->name('import');
        Route::get('/qrs/{id}', 'Access\AccessController@qrs')->name('qrs');
    });

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')

    <header class="content__title">
        <h1>Dashboard</h1>
    </header>

    <div class="row">
        <div class="col-sm-6 col-md-3">
            <div class="quick-stats__item bluegray-light-bg">
                <div class="quick-stats__info">
                    <h2>${{ number_format($total, 2, '.', ',') }}</h2>
                    <small>Ventas totales</small>
                </div>

                <div class="quick-stats__chart sparkline-bar-stats">6,4,8,6,5,6,7,8,3,5,9,5,</div>
            </div>
        </div>

        <div class="col-sm-6 col-md-3">
            <div class="quick-stats__item bluegray-light-bg">
                <div class="quick-stats__info">
                    <h2>987,459</h2>
                    <small>Vistas sitio web</small>
                </div>

                <div class="quick-stats__chart sparkline-bar-stats">7,8,3,5,9,5,6,4,8,6,5,6,</div>
            </div>
        </div>

        <div class="col-sm-6 col-md-3">
            <div class="quick-stats__item bluegray-light-bg">
                <div class="quick-stats__info">
                    <h2>$987,459</h2>
                    <small>Accesos utilizados</small>
                </div>

                <div class="quick-stats__chart sparkline-bar-stats">6,5,6,7,8,6,4,8,3,5,9,5</div>
            </div>
        </div>

        <div class="col-sm-6 col-md-3">
            <div class="quick-stats__item bluegray-light-bg">
                <div class="quick-stats__info">
                    <h2>{{ $ticket_shop}}</h2>
                    <small>Total de boletos vendidos</small>
                </div>

                <div class="quick-stats__chart sparkline-bar-stats">6,4,8,6,5,6,7,8,3,5,9,5</div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-12 col-md-6">
                <div class="card icons-demo">
                    <div class="card-body">
                        <canvas id="myChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card icons-demo">
                <div class="card-body">
                    <h4 class="card-title">Próximos eventos</h4>
                    <h6 class="card-subtitle">Listado de los próximos eventos y su estado</h6>
                    <p class="card-text">
                        @foreach($upcoming_events as $upcoming_event)
                            <a href="{{ route('system.events.show', [session('system_slug'), $upcoming_event->id]) }}" target="_self">
                                <button class="btn btn-light btn-outline-{{ ($upcoming_event->active ? 'success' : 'secondary') }} btn-block btn--raised btn--icon-text text-left m-b-20">
                                    <i class="zmdi zmdi-{{ ($upcoming_event->on_sale ? 'money' : 'money-off') }} zmdi-hc-fw"></i>
                                    {{ $upcoming_event->name }}

                                    <small class="pull-right" style="color: #607D8B;">{{ $upcoming_event->datespan() }}</small>
                                </button>
                            </a>
                        @endforeach
                    </p>


                    <p class="card-text m-t-40">
                        <hr>
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Inactivo</button>
                            <button type="button" class="btn btn-sm btn-outline-success">Activo</button>
                        </div>
                        <br /><br />
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-sm ">
                                <i class="zmdi zmdi-money zmdi-hc-fw"></i> = A la venta
                            </button>
                            <button type="button" class="btn btn-sm ">
                                <i class="zmdi zmdi-money-off zmdi-hc-fw"></i> = Sin vender
                            </button>
                        </div>
                    </p>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-6">
            <div class="card icons-demo">
                <div class="card-body">
                    <h4 class="card-title">Eventos activos</h4>
                    <h6 class="card-subtitle">Listado de los eventos marcados como activos</h6>
                    <p class="card-text">
                        @foreach($active_events as $active_event)
                            <a href="{{ route('system.events.show', [session('system_slug'), $active_event->id]) }}" target="_self">
                                <button class="btn btn-light btn-outline-success btn-block btn--raised btn--icon-text text-left m-b-20">
                                    <i class="zmdi zmdi-{{ ($active_event->on_sale ? 'money' : 'money-off') }} zmdi-hc-fw"></i>
                                    {{ $active_event->name }}

                                    <small class="pull-right" style="color: #607D8B;">{{ $active_event->datespan() }}</small>
                                </button>
                            </a>
                        @endforeach
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('after_includes')
<script src="{{ Asset('/assets/material/demo/js/other-charts.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<script type="text/javascript">
    var fechas = [@foreach($labes as $l) "{{ $l }}", @endforeach];
    console.log(fechas);


    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'bar',

        // The data for our dataset
        data: {
            labels: fechas,
            datasets: [{
                label: 'ventas por dia',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: {{ json_encode($data) }}
            }]
        },

        // Configuration options go here
        options: {}
    });



    'use strict';

    $(document).ready(function () {
        /*---------------------------------------
        jQuery Sparklines
        ----------------------------------------*/

        // Quick stats bar chart
        if($('.sparkline-bar-stats')[0]) {
            $('.sparkline-bar-stats').sparkline('html', {
                type: 'bar',
                height: 36,
                barWidth: 3,
                barColor: '#fff',
                barSpacing: 2
            });
        }

        //Sample Sparkline Line Chart
        if ($('.sparkline-line')[0]) {
            $('.sparkline-line').sparkline('html', {
                type: 'line',
                width: '100%',
                height: 50,
                lineColor: '#39bbb0',
                fillColor: 'rgba(0,0,0,0)',
                lineWidth: 1,
                maxSpotColor: '#39bbb0',
                minSpotColor: '#39bbb0',
                spotColor: '#39bbb0',
                spotRadius: 4,
                highlightSpotColor: '#39bbb0',
                highlightLineColor: '#39bbb0'
            });
        }

        //Sample Sparkline Bar Chart
        if ($('.sparkline-bar')[0]) {
            $('.sparkline-bar').sparkline('html', {
                type: 'bar',
                height: 40,
                barWidth: 3,
                barColor: '#03A9F4',
                barSpacing: 2
            });
        }

        //Sample Sparkline Tristate Chart
        if ($('.sparkline-tristate')[0]) {
            $('.sparkline-tristate').sparkline('html', {
                type: 'tristate',
                height: 40,
                posBarColor: '#32c787',
                zeroBarColor: '#32c787',
                negBarColor: '#f5c942',
                barWidth: 3,
                barSpacing: 2
            });
        }

        //Sample Sparkline Discrete Chart
        if ($('.sparkline-discrete')[0]) {
            $('.sparkline-discrete').sparkline('html', {
                type: 'discrete',
                height: 40,
                lineColor: '#00BCD4',
                thresholdColor: '#d066e2',
                thresholdValue: 4
            });
        }

        //Sample Sparkline Bullet Chart
        if ($('.sparkline-bullet')[0]) {
            $('.sparkline-bullet').sparkline('html', {
                type: 'bullet',
                targetColor: '#fff',
                performanceColor: '#03A9F4',
                rangeColors: ['#ff6b68', '#fc7f7d', '#fc918f'],
                width: '100%',
                height: 50
            });
        }

        //Sample Sparkline Pie Chart
        if ($('.sparkline-pie')[0]) {
            $('.sparkline-pie').sparkline('html', {
                type: 'pie',
                height: 50,
                sliceColors: ['#f5c942', '#ff6b68', '#03A9F4', '#32c787']
            });
        }

        /*---------------------------------------
        Easy Pie Charts
        ----------------------------------------*/
        if($('.easy-pie-chart')[0]) {
            $('.easy-pie-chart').each(function () {
                var value = $(this).data('value');
                var size = $(this).data('size');
                var trackColor = $(this).data('track-color');
                var barColor = $(this).data('bar-color');

                $(this).find('.easy-pie-chart__value').css({
                    lineHeight: (size)+'px',
                    fontSize: (size/4)+'px',
                    color: barColor
                });

                $(this).easyPieChart ({
                    easing: 'easeOutBounce',
                    barColor: barColor,
                    trackColor: trackColor,
                    scaleColor: 'rgba(0,0,0,0)',
                    lineCap: 'round',
                    lineWidth: 2,
                    size: size,
                    animate: 3000,
                    onStep: function(from, to, percent) {
                        $(this.el).find('.percent').text(Math.round(percent));
                    }
                })
            });
        }
    });
</script>
@endsection

resources/views/admin/prices.blade.php
@extends('layouts.app')

@section('content')
    <header class="content__title">
        <h1>Precios</h1>
    </header>


    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card icons-demo">
                <div class="card-body">
                    <h4 class="card-title">Total ventas</h4>
                    <h6 class="card-subtitle">Praesent commodo cursus magna scelerisque consectetur.</h6>
                    <p class="card-text">Aenean lacinia bibendum nulla sed consectetur. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec sed odio dui. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.</p>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-6">
            <div class="card icons-demo">
                <div class="card-body">
                    <h4 class="card-title">Resumen ventas</h4>
                    <h6 class="card-subtitle">Praesent commodo cursus magna scelerisque consectetur.</h6>
                    <p class="card-text">Aenean lacinia bibendum nulla sed consectetur. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec sed odio dui. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.</p>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/root_dashboard.blade.php
@extends('layouts.app')

@section('content')

    <header class="content__title">
        <h1>Root Dashboard</h1>
    </header>

    <div class="col-sm-12 col-md-8 offset-md-2">
        <header class="content__title text-center">
            <h1>Elige el sistema que quieres administrar</h1>
        </header>

        <div class="row">
            @foreach($systems as $system)
                <a href="{{ route('system.dashboard', $system->slug) }}" target="_self" class="col-sm-12 col-md-6 text-center m-b-15 system-card-container">
                    <div class="card system-card">
                        <div class="card-body">
                            <h2>{{ $system->name }}</h2>
                            <div class="col-sm-6 offset-sm-3 m-t-25 m-b-25">
                                <img src="{{ Storage::url($system->img_path(false)) }}" class="img-fluid system-img" />
                            </div>
                            <hr>
                            <small>{{ $system->slug }}</small>
                        </div>
                    </div>
                </a>
            @endforeach
        </div>
    </div>
@endsection

resources/views/admin/sales.blade.php
@extends('layouts.app')

@section('content')
    <header class="content__title">
        <h1>Ventas</h1>
    </header>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Ventas últimos 14 días</h4>

                    <div id="flot-line-1" class="flot-chart flot-line"></div>
                    <div class="flot-chart-legends flot-chart-legends--line"></div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Ventas últimos 30 días</h4>

                    <div id="flot-line-2" class="flot-chart flot-line"></div>
                    <div class="flot-chart-legends flot-chart-legends--line"></div>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card icons-demo">
                <div class="card-body">
                    <h4 class="card-title">Total ventas</h4>
                    <h6 class="card-subtitle">Praesent commodo cursus magna scelerisque consectetur.</h6>
                    <p class="card-text">Aenean lacinia bibendum nulla sed consectetur. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec sed odio dui. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.</p>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-6">
            <div class="card icons-demo">
                <div class="card-body">
                    <h4 class="card-title">Resumen ventas</h4>
                    <h6 class="card-subtitle">Praesent commodo cursus magna scelerisque consectetur.</h6>
                    <p class="card-text">Aenean lacinia bibendum nulla sed consectetur. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec sed odio dui. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.</p>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('after_includes')
<script src="{{ Storage::url('assets/material/vendors/flot/jquery.flot.js') }}"></script>
<script src="{{ Storage::url('assets/material/vendors/flot/jquery.flot.resize.js') }}"></script>

<script type="text/javascript">
'use strict';

$(document).ready(function(){
    // Chart Data
    var lineChartData1 = [
        {
            label: 'General',
            data: [[1,40], [2,35], [3,37], [4,100], [5,10], [6,90], [7,15]],
            color: '#32c787'
        },
        {
            label: 'Platea',
            data: [[1,25], [2,70], [3,60], [4,70], [5,100], [6,35], [7,75]],
            color: '#03A9F4'
        },
        {
            label: 'Palco',
            data: [[1,10], [2,20], [3,60], [4,90], [5,30], [6,10], [7,5]],
            color: '#f5c942'
        }
    ];

    var lineChartData2 = [
        {
            label: 'General',
            data: [[1,20], [2,90], [3,60], [4,40], [5,100], [6,25], [7,65]],
            color: '#32c787'
        },
        {
            label: 'Platea',
            data: [[1,100], [2,20], [3,60], [4,90], [5,80], [6,10], [7,5]],
            color: '#03A9F4'
        },
        {
            label: 'Palco',
            data: [[1,60], [2,30], [3,50], [4,100], [5,10], [6,90], [7,85]],
            color: '#f5c942'
        }
    ];

    // Chart Options
    var lineChartOptions = {
        series: {
            lines: {
                show: true,
                barWidth: 0.05,
                fill: 0
            }
        },
        shadowSize: 0.1,
        grid : {
            borderWidth: 1,
            borderColor: '#edf9fc',
            show : true,
            hoverable : true,
            clickable : true
        },

        yaxis: {
            tickColor: '#edf9fc',
            tickDecimals: 0,
            font :{
                lineHeight: 13,
                style: 'normal',
                color: '#9f9f9f',
            },
            shadowSize: 0
        },

        xaxis: {
            tickColor: '#fff',
            tickDecimals: 0,
            font :{
                lineHeight: 13,
                style: 'normal',
                color: '#9f9f9f'
            },
            shadowSize: 0,
        },
        legend:{
            container: '.flot-chart-legends--line',
            backgroundOpacity: 0.5,
            noColumns: 0,
            backgroundColor: '#fff',
            lineWidth: 0,
            labelBoxBorderColor: '#fff'
        }
    };

    // Create chart
    $.plot($('#flot-line-1'), lineChartData1, lineChartOptions);
    $.plot($('#flot-line-2'), lineChartData2, lineChartOptions);
});

</script>
@endsection