routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

Auth::routes(['verify' => true]);


Route::middleware('auth')->group(function () {
    Route::get('/', 'SiteController@home');
    Route::get('/elegir_sistema', 'SystemController@index')->name('system.select');
    Route::get('/dashboard/root', 'AdminController@root_dashboard')->name('root.dashboard');
});

Route::name('admin.')->middleware('auth')->group(function () {
    Route::resource('/sistemas', 'SystemController', ['names' => 'system']);
});

// TDS Routes
Route::post('/tds/activacion', 'TicketDistributionSystem\TicketDistributionSystemController@account_activation')->name('tds.account.activation');
Route::get('/tds/{id}/registro', 'TicketDistributionSystem\TicketDistributionSystemController@register')->name('tds.register');
Route::post('/tds/logout', 'TicketDistributionSystem\TicketDistributionSystemController@logout')->name('tds.logout');
Route::post('/tds/login', 'TicketDistributionSystem\TicketDistributionSystemController@login')->name('tds.login');
Route::get('/tds/login', 'TicketDistributionSystem\TicketDistributionSystemController@login_form')->name('tds.login.form');
Route::get('/tds', 'TicketDistributionSystem\TicketDistributionSystemController@index')->middleware('auth:client_users')->name('tds');
Route::get('/tds/{id}/asignar', 'TicketDistributionSystem\TicketDistributionSystemController@assign')->middleware('auth:client_users')->name('tds.assign');

// TDS password reset
Route::get('/tds/password/request', 'TicketDistributionSystem\TicketDistributionSystemController@password_request_form')->name('tds.password.request.form');
Route::get('/tds/{id}/password/reset', 'TicketDistributionSystem\TicketDistributionSystemController@password_reset_form')->name('tds.password.reset.form');
Route::post('/tds/email/reenviar', 'TicketDistributionSystem\TicketDistributionSystemController@resend_email')->middleware('auth:client_users')->name('tds.email.resend');
Route::post('/tds/password/request', 'TicketDistributionSystem\TicketDistributionSystemController@password_request')->name('tds.password.request');
Route::post('/tds/password/reset', 'TicketDistributionSystem\TicketDistributionSystemController@password_reset')->name('tds.password.reset');

// TDS Exports
Route::post('/tds/exportar', 'TicketDistributionSystem\TicketDistributionSystemController@export')->name('tds.export');


// Subdomain routes
Route::domain('{system}.' . env('APP_BASE_DOMAIN'))->name('system.')->middleware('auth')->group(function () {
    // Route::prefix('{pumastabasco}')->name('system.')->middleware('auth')->group(function () {
    Route::get('/', 'AdminController@dashboard_redirect');

    // System dashboard
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

    // Events
    Route::prefix('/eventos')->name('events.')->group(function () {
        // Event groups resource
        Route::resource('/grupos', 'EventGroupController', ['names' => 'groups']);
        Route::post('/grupos/{id}/upload_img', 'EventGroupController@upload_img')->name('groups.upload.imgs');
        Route::put('/grupos/{id}/update/ticket_types', 'EventGroupController@updateTicketTypes')->name('groups.update.ticket_types');
        Route::get('/grupos/{id}/general', 'EventGroupController@general')->name('groups.general');
        Route::get('/grupos/{id}/holding', 'EventGroupController@holding')->name('groups.holding');
        Route::get('/grupos/{id}/boletos', 'EventGroupController@orders')->name('groups.orders');
        Route::get('/grupos/{id}/zonas', 'EventGroupController@zones')->name('groups.zones');
        Route::get('/grupos/{id}/{order_id}/qrs', 'OrderController@qrs')->name('groups.order.qrs');
        Route::get('/grupos/{id}/boletos/generar', 'EventGroupController@ticket_qrs_single_page')->name('groups.season.tickets.generateQRs');

        // All, by venue or team
        Route::get('/todos', 'EventController@all')->name('all');
        Route::get('/sede/{venue}', 'EventController@byVenue')->name('byVenue');
        Route::get('/equipo/{team}', 'EventController@byTeam')->name('byTeam');

        // Edit
        Route::post('/{id}/upload_img', 'EventController@upload_img')->name('upload.imgs');
        Route::get('/{id}/change_status', 'EventController@change')->name('status');

        // Holding
        Route::get('/{id}/holding', 'EventController@holding')->name('tickets.holding');

        // Statistics | Readings | Tickets | Courtesy | Accreditations
        Route::get('/{id}/estadisticas', 'EventController@statistics')->name('statistics');
        Route::get('/{id}/estadisticas/generales', 'EventController@general_statistics')->name('general.statistics');
        Route::post('/{id}/estadisticas/pdf', 'EventController@stadistic_pdf')->name('statistics.pdf');
        Route::get('/{id}/estadisticas/procesar', 'EventController@processStatistics')->name('statistics.process');
        Route::get('/{id}/lecturas', 'EventController@ticket_readings')->name('tickets.readings');
        Route::get('/{id}/boletos', 'EventController@ticket_list')->name('tickets.list'); // Ticket
        Route::get('/{id}/boletos/generar', 'EventController@tickets_generate')->name('tickets.generate');

        Route::get('/{id}/boletos/generarQRs', 'EventController@ticket_qrs_single_page')->name('tickets.generateForEvent');
        Route::get('/{id}/boletos/reporte', 'EventController@order_report')->name('tickets.order_report');
        Route::post('/{id}/boletos/buscar', 'EventController@search')->name('tickets.search');
        Route::get('/{id}/cortesias', 'EventController@courtesy_list')->name('courtesy.list');
        Route::get('/{id}/cortesias/generar', 'EventController@courtesy_qrs_single_page')->name('courtesy.generateForEvent');
        Route::get('/{id}/acreditaciones', 'EventController@accreditations_list')->name('accreditations.list');
        Route::post('/{id}/distribucion', 'EventController@send_ticket_distribution')->name('tickets.distribution.send');
        Route::get('/{id}/distribucion/{ticket_group}/reenviar', 'EventController@resend_email')->name('tickets.distribution.resend');
        Route::get('/{id}/distribucion', 'EventController@ticket_distribution')->name('tickets.distribution');

        // Analysis
        Route::get('/{id}/analisis', 'EventController@analysis')->name('analysis');

        // Season tickets
        Route::get('/{id}/abonos', 'AccreditationController@seasonTickets')->name('season.tickets');
        Route::get('/{id}/abonos/generar', 'AccreditationController@generateSeasonTickets')->name('season.tickets.generate');
        Route::get('/{id}/abonos/{season_ticket}', 'AccreditationController@show')->name('season.tickets.show');

        // Order QRs
        Route::get('/{id}/{order_id}/qrs', 'OrderController@qrs')->name('order_qrs');

        // Cortesias group
        Route::prefix('/{id}/acreditaciones')->name('accreditations.')->group(function () {
            // Route::get('/seleccionar', 'EventController@accreditations')->name('selection'); // Vista usuario acreditaciones
            Route::get('/confirmar', 'AccreditationController@confirm_accreditations')->name('confirm');
            Route::get('/guardar', 'AccreditationController@store')->name('store');
            Route::get('/generar', 'EventController@generateAccreditations')->name('generateForEvent'); // Vista usuario acreditaciones

            Route::get('/{order}/detalle', 'OrderController@courtesy_detail')->name('courtesies.detail');

            Route::get('/{accreditation}', 'AccreditationController@show')->name('show');
            Route::put('/{accreditation}/update', 'AccreditationController@update')->name('update');
            // Route::get('/{accreditation}/show', 'AccreditationController@show')->name('show');
        });
    });

    // Resource
    Route::resource('/eventos', 'EventController', ['names' => 'events']);


    // Orders
    Route::resource('/ordenes', 'OrderController', ['names' => 'orders'])->except(['edit, update']);
    Route::post('/ordenes/{id}', 'OrderController@update')->name('orders.update');
    Route::get('/ordenes/{id}/pdf', 'OrderController@pdf')->name('courtesy.pdf');
    Route::get('/ordenes/{id}/email/resend', 'OrderController@resend_email')->name('orders.resend.email');
    // Route::get('/ordenes/{id}/qr', 'OrderController@Qrs');
    // Route::get('qrImage/{order_id}/{type}', 'SiteController@qrImage');
    // Route::resource('/temas', 'TopicController');
    // Route::get('/soporte', 'SupportController@index');
    // Route::get('/soporte/{id}/estado/{status}', 'SupportController@change_status');

    // Accreditations
    Route::prefix('/acreditaciones')->name('accreditations.')->group(function () {
        // Route::get('/', 'AccreditationController@index')->name('index');
        Route::get('/detalle/{id}', 'AccreditationController@accreditation_history')->name('details');
        Route::get('/qrs', 'AccreditationController@qr')->name('qr');
        Route::get('/qrs/{id}', 'AccreditationController@qr')->name('qrByTeam');
        Route::get('/importar', 'ImportController@index')->name('import');
        Route::post('/import', 'ImportController@import')->name('import.file');
        Route::post('/version/{acreditation}', 'AccreditationController@change_version')->name('version');
    });
    Route::resource('/acreditaciones', 'AccreditationController', ['names' => 'accreditations'])->except(['edit', 'destroy']);

    // Access
    Route::prefix('/accesos')->name('access.')->group(function () {
        Route::get('/reportes', 'Access\ReportController@reports')->name('reports');
        Route::get('/reportes/{id}', 'Access\ReportController@report')->name('report');
        Route::post('/importar', 'ImportController@import_access')->name('import');
        Route::get('/qrs/{id}', 'Access\AccessController@qrs')->name('qrs');
    });

app/Http/Controllers/POS/EventController.php
<?php

namespace App\Http\Controllers\POS;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Event;
use App\EventSeatAvailability;

class EventController extends Controller
{
    public function events(Request $request)
    {
        // Returning data
        return [
            'error' => false,
            'events' => Event::upcoming_on_sale_events(),
        ];
    }

    public function eventsSlideshow(Request $request)
    {
        // Returning data
        return [
            'error' => false,
            'slideshows' => Event::upcoming_on_sale_events_slideshow(),
        ];
    }

    public function event(Request $request)
    {
        // Event
        $ev = Event::find($request->event_id);

        // Checking if event is still on sale
        if (!$ev->on_sale) {
            // Returning data
            return [
                'error' => true,
                'error_message' => 'Este evento ya no se encuentra disponible',
            ];
        }

        // Compiling event info
        $ticket_types = array();

        foreach ($ev->ticket_template->ticket_types as $type) {
            if ($type->active == 1) {
                $seats = EventSeatAvailability::seatsForEventAndTicket($ev->id, $type->id);

                if ($seats->available > 0) {
                    // Grouping by zones in Villahermosa stadium
                    $zone = $type->zone->API();
                    $ticket_types[$zone['parent_zone']['id']]['tickets'][$type->id] = [
                        'id' => $type->id,
                        'name' => $type->name,
                        'color' => '#' . $type->color,
                        'zone' => $zone,
                        'price' => number_format($type->pivot->price, 2, '.', ','),
                        'active' => $type->active,
                        'available' => $seats->available,
                    ];

                    $ticket_types[$zone['parent_zone']['id']]['type'] = $type->type;
                    $ticket_types[$zone['parent_zone']['id']]['name'] = $zone['parent_zone']['name']; // TODO Fetch zones by groups, because this is a shitty solution
                    $ticket_types[$zone['parent_zone']['id']]['color'] = '#' . $type->color; // TODO define zone color, because this is a shitty solution
                }
            }
        }

        // Returning data
        return [
            'error' => false,
            'event' => [
                'id' => $ev->id,
                'event' => $ev->name,
                'event_date' => $ev->date,
                'active' => $ev->active,
                'on_sale' => $ev->on_sale,
                'id_venue' => $ev->venue->id,
                'venue' => $ev->venue->name,
            ],
            'ticket_types' => $ticket_types,
            // 'stadium_configuration' => $ev->venue->stadiumConfiguration()
        ];
    }
}

app/Http/Livewire/Events/Accreditations/AccreditationsList.php
<?php

namespace App\Http\Livewire\Events\Accreditations;

use Livewire\Component;
use Livewire\WithPagination;

class AccreditationsList extends Component
{
    // Pagination
    use WithPagination;
    protected $paginationTheme = 'bootstrap';

    // Event
    public $event;

    // Mount
    public function mount($event)
    {
        $this->event = $event;
    }

    // Render
    public function render()
    {
        return view('livewire.events.accreditations.accreditations-list', [
            'accreditations' => $this->event->assigned_accreditations()->where('type', 'operative')->paginate(15)
        ]);
    }
}

app/Http/Livewire/Events/Courtesies/CourtesyList.php
<?php

namespace App\Http\Livewire\Events\Courtesies;

use Livewire\Component;
use Livewire\WithPagination;

class CourtesyList extends Component
{
    // Pagination
    use WithPagination;
    protected $paginationTheme = 'bootstrap';

    // Event
    public $event;

    // Mount
    public function mount($event)
    {
        $this->event = $event;
    }

    // Render
    public function render()
    {
        return view('livewire.events.courtesies.courtesy-list', [
            'courtesies' => $this->event->courtesy_orders()->paginate(15)
        ]);
    }
}

app/Http/Livewire/Events/Orders/OrdersList.php
<?php

namespace App\Http\Livewire\Events\Orders;

use Livewire\Component;
use Livewire\WithPagination;

class OrdersList extends Component
{
    // Pagination
    use WithPagination;
    protected $paginationTheme = 'bootstrap';

    // Event
    public $event;

    // Mount
    public function mount($event)
    {
        $this->event = $event;
    }

    // Render
    public function render()
    {
        return view('livewire.events.orders.orders-list', [
            'orders' => $this->event->regular_orders()->paginate(15)
        ]);
    }
}

app/Http/Livewire/Events/SeassonTickets/SeassonTicketsList.php
<?php

namespace App\Http\Livewire\Events\SeassonTickets;

use Livewire\Component;
use Livewire\WithPagination;

class SeassonTicketsList extends Component
{
    // Pagination
    use WithPagination;
    protected $paginationTheme = 'bootstrap';

    // Event
    public $event;

    // Mount
    public function mount($event)
    {
        $this->event = $event;
    }

    // Render
    public function render()
    {
        return view('livewire.events.seasson-tickets.seasson-tickets-list', [
            'seasson_tickets' => $this->event->assigned_accreditations()->where('type', 'season_ticket')->paginate(15)
        ]);
    }
}

app/Http/Livewire/Events/TicketGenerator/TicketGenerator.php
<?php

namespace App\Http\Livewire\Events\TicketGenerator;

use Livewire\Component;
use Illuminate\Support\Facades\Artisan;

class TicketGenerator extends Component
{
    // Event
    public $eventId;
    public $orderAmount;
    public $ticketsPerOrder;
    public $ticket_type_id;
    public $type;
    public $courtesy;
    public $ticketPrice;


    // Mount
    public function mount($eventId, $courtesy)
    {
        $this->eventId = $eventId;
        $this->courtesy = $courtesy;
    }

    public function render()
    {
        return view('livewire.events.ticket-generator.ticket-generator', [
            ''
        ]);
    }

    public function createOrders()
    {
        // Cleaning DB
        // Artisan::call('clean:server');
    }

    // create:orders {event_id} {order_amount} {tickets_per_order} {ticket_type_id} {user_id} {type} {courtesy} {ticket_price}
    // php artisan create:orders 71 133 1 313 1 other true 0.00
}

resources/views/admin/events/groups/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <header class="content__title">
                <h1>Crear grupo de eventos</h1>
            </header>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <div class="card">
                <div class="card-body">
                    {!! Form::open(array('url' => route('system.events.groups.store', $system->slug), 'method' => 'POST', 'enctype' => 'multipart/form-data')) !!}
                        {!! Form::MDtext('Nombre', 'name', old('name'), $errors) !!}
                        {!! Form::MDtext('Slug', 'slug', old('slug'), $errors) !!}
                        {!! Form::MDtext('Subtítulo', 'tagline', old('tagline'), $errors) !!}
                        {!! Form::MDtextarea('Descripción', 'description', old('description'), $errors) !!}

                        {!! Form::MDsubmit('Crear', 'create', ['icon' => 'plus-circle-o']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/events/groups/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <header class="content__title">
                <h1>Editar {{ $event_group->name }}</h1>
            </header>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8 offset-2">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Datos generales</h4>
                            {!! Form::open(array('url' => route('system.events.groups.update', [session('system_slug'), $event_group->id]), 'method' => 'PUT', 'enctype' => 'multipart/form-data')) !!}
                                {!! Form::MDtext('Nombre', 'name', old('name') ?? $event_group->name, $errors) !!}
                                {!! Form::MDtext('Slug', 'slug', old('slug') ?? $event_group->slug, $errors, ['disabled' => true]) !!}
                                {!! Form::MDtext('Subtítulo', 'tagline', old('tagline') ?? $event_group->tagline, $errors) !!}
                                {!! Form::MDtextarea('Descripción', 'description', old('description') ?? $event_group->description, $errors) !!}
                                {!! Form::MDselectize('Eventos', 'events', \App\Event::selectize(), $selected_events, $errors) !!}

                                {!! Form::MDToggleSwitch('Abonos en venta', 'accreditations_on_sale', $event_group->accreditations_on_sale, $errors) !!}

                                {!! Form::MDsubmit('Guardar', 'edit', ['icon' => 'plus-circle-o']) !!}
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Imágen</h4>
                            <div class="row">
                                {!! Form::MDdropzone('', 'img', route('system.events.groups.upload.imgs', [session('system_slug'), $event_group->id]), $errors, ['leyend' => 'Tamaño: 600x600 px']) !!}
                                <div class="col-sm-12 m-t-15">
                                    <img class="center img-fluid" src="{{ asset($event_group->img_path()) }}" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Imágen promocional</h4>
                            <div class="row">
                                {!! Form::MDdropzone('', 'img_slideshow', route('system.events.groups.upload.imgs', [session('system_slug'), $event_group->id]), $errors, ['accepted-files' => '.jpg, .jpeg', 'leyend' => 'Tamaño: 600x600 px']) !!}
                                <div class="col-sm-12 m-t-15">
                                    <img class="center img-fluid" src="{{ asset($event_group->img_slideshow_path()) }}" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
@endsection

resources/views/admin/events/groups/orders.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <header class="content__title">
                <h1>{{ $event_group->system->teams->first()->name }} - {{ $event_group->name }} | Abonos</h1>

                <div class="actions actions--calendar">
                    @if(in_array(Auth::user()->type , ['root', 'admin', 'courtesies']))
                        <a href="{{ route('system.events.groups.season.tickets.generateQRs', [session('system_slug'), $event_group->id]) }}" target="_blank" class="btn btn-outline-secondary btn-light1 btn--raised btn--icon-text">
                            <i class="zmdi zmdi-accounts-list"></i> Imprimir QRs
                        </a>
                    @endif
                </div>
            </header>
        </div>
    </div>

    <div class="row p-t-25 p-b-25">
        <div class="col-sm-12">
            @include('admin.events.groups.elements.nav_tabs', ['selected' => 'orders'])
        </div>
    </div>

    @if($event_group->orders->count() > 0)
        <div class="row">
            <div class="col-sm-12">
                <header class="content__title">
                    <h1>Órdenes y abonos registrados</h1>
                </header>
            </div>
        </div>

        <div class="row">
            @foreach($event_group->orders()->orderBy('created_at', 'DESC')->get() as $order)
                <div class="col-sm-6">
                    <div class="card p-0">
                        <div class="card-body">
                            <h4 class="card-title">
                                #{{ $order->id }} - {{ $order->client_user->full_name() }}

                                <div class="actions pull-right">
                                    <a href="#edit-order-{{ $order->id }}" data-toggle="modal" data-target="#edit-order-{{ $order->id }}" class="btn btn-outline-secondary btn--raised btn--icon-text">
                                        <i class="zmdi zmdi-edit"></i> Orden
                                    </a>
                                    <a href="{{ route('system.orders.resend.email', [session('system_slug'), $order->id]) }}" class="btn btn-outline-secondary btn--raised btn--icon-text btn-resend">
                                        <i class="zmdi zmdi-mail-send zmdi-hc-fw"></i> Reenviar correo
                                    </a>
                                    <a href="{{ route('system.orders.show', [session('system_slug'), $order->id]) }}" class="btn btn-outline-secondary btn--raised btn--icon-text">
                                        <i class="fas fa-eye"></i> Ver
                                    </a>
                                    @if ($order->type == 'season_ticket')
                                        <a href="{{ route('system.events.groups.order.qrs', [session('system_slug'), $event_group->id, $order->id]) }}" target="_blank" class="btn btn-outline-secondary btn--raised btn--icon-text">
                                            <i class="fas fa-qrcode"></i> QRs
                                        </a>
                                    @else
                                        <a href="{{ route('system.events.order_qrs', [session('system_slug'), $event_group->id, $order->id]) }}" target="_blank" class="btn btn-outline-secondary btn--raised btn--icon-text">
                                            <i class="fas fa-qrcode"></i> QRs
                                        </a>
                                    @endif
                                </div>
                            </h4>
                            <h6 class="card-subtitle">
                                {{ $order->email }} <br />
                                {{ $order->created_at }}
                            </h6>

                            <p class="card-text">
                                <div class="table-responsive">
                                    <table class="table table-bordered data-table2">
                                        <thead class="thead-default">
                                            <tr>
                                                <th class="col-sm-6">Zona | Asiento</th>
                                                <th class="col-sm-2 text-center">Cantidad</th>
                                                <th class="col-sm-2 text-right">Precio</th>
                                                <th class="col-sm-2 text-right">Subtotal</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($order->seasson_tickets as $ticket)
                                                <tr>
                                                    <td>
                                                        {{ $ticket->ticket_type->name }}
                                                        @if ($ticket->seat)
                                                        | {{ $ticket->seat->row->name }} - {{ $ticket->seat->name }}
                                                        @else
                                                            General
                                                        @endif
                                                        </td>
                                                    <td class="text-center">{{ $ticket->amount }}</td>
                                                    <td class="text-right">{{ pretty_money($ticket->price) }}</td>
                                                    <td class="text-right">{{ pretty_money($ticket->amount*$ticket->price) }}</td>
                                                </tr>
                                            @endforeach

                                            <tr>
                                                <td colspan="3" class="text-right">Total:</td>
                                                <td  class="text-right">
                                                    <strong>{{ pretty_money($order->total) }}</strong>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @else
        <div class="col-sm-12 text-center" style="opacity: 0.5">
                NO HAY ORDENES REGISTRADAS
        </div>
    @endif

@foreach($event_group->orders()->orderBy('created_at', 'DESC')->get() as $order)
    @include('admin.orders.modals.edit')
@endforeach
@endsection
    
@section('after_includes')
<script>
    $('.btn-resend').on('click', function(e){
        if(!confirm('¿Estás seguro de querer reenviar el correo de confirmación de compra?')){
            e.preventDefault();
        }
    });
</script>
@endsection

resources/views/admin/events/groups/zones.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <header class="content__title">
                <h1>Zonas y precios | {{ $event_group->name }}</h1>
            </header>
        </div>
    </div>

    <div class="row p-t-25 p-b-25">
        <div class="col-sm-12">
            @include('admin.events.groups.elements.nav_tabs', ['selected' => 'zones'])
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8 offset-2">
            <div class="card">
                <div class="card-body">
                    {!! Form::open(array('url' => route('system.events.groups.update.ticket_types', [session('system_slug'), $event_group->id]), 'method' => 'PUT', 'enctype' => 'multipart/form-data')) !!}
                        <h4 class="card-title">Tipos de tickets</h4>
                        <h6 class="card-subtitle">Selecciona los tipos de tickets a vender como abono.<br />Ingresa el número máximo de abnos a vender y su precio</h6>


                        @foreach($system->venues as $venue)
                            <div class="row p-t-25 p-b-25">
                                <div class="col-sm-12">
                                    <h3 class="card-subtitle">{{ $venue->name }}</h3>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-2 strong">Tipo de boleto</div>
                                <div class="col-sm-2 strong">Max. venta</div>
                                <div class="col-sm-2 strong">Precio</div>

                                <div class="col-sm-2 strong">Tipo de boleto</div>
                                <div class="col-sm-2 strong">Max. venta</div>
                                <div class="col-sm-2 strong">Precio</div>

                                <div class="col-sm-12"><hr></div>
                            </div>

                            <div class="row">
                                @foreach($venue->ticket_types_relation as $ticket_type)
                                    {!! Form::MDToggleSwitch($ticket_type->name, 'tt_'.$ticket_type->id, (array_key_exists($ticket_type->id, $compressed_ticket_types) ? true : false), $errors, ['class' => 'col-sm-2']) !!}
                                    {!! Form::MDtext('', $ticket_type->id.'_total', (array_key_exists($ticket_type->id, $compressed_ticket_types) ? $compressed_ticket_types[$ticket_type->id]['total'] : false), $errors, ['class' => 'col-sm-2']) !!}
                                    {!! Form::MDtext('', $ticket_type->id.'_price', (array_key_exists($ticket_type->id, $compressed_ticket_types) ? $compressed_ticket_types[$ticket_type->id]['price'] : false), $errors, ['class' => 'col-sm-2']) !!}
                                @endforeach
                            </div>
                        @endforeach

                        {!! Form::MDsubmit('Guardar', 'edit', ['icon' => 'plus-circle-o']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection